# Generated by Django 4.1.2 on 2022-10-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('feedback', models.CharField(max_length=200, verbose_name='Review')),
            ],
        ),
    ]
